name: TNX
version: 0.2
author: Tonix1508
api-version: 1.14
main: de.wiese_christoph.tnx.Main

commands:
     vote:
      description: Vote for day, night, clear or rain.
      usage: /<command> <day|night|clear|rain>
      permission: tnx.vote
     rocket:
      description: Launch a player in the air and let him explode.
      usage: /<command> <player>
      permission: tnx.rocket
     ce:
      description: Enable ord disable Creeper Explosion protection.
      usage: /<command> <true|false>
      permission: tnx.ce
     bp:
      description: Enable ord disable Bed Percentage night skip.
      usage: /<command> <true|false>
      permission: tnx.bp
     tv:
      description: Enable ord disable Time Vote.
      usage: /<command> <true|false>
      permission: tnx.tve
     bb:
      description: Create a BossBar Broadcast Message.
      usage: /<command> <message>
      permission: tnx.bb
     