name: TNX
version: 0.5
author: Tonix1508
api-version: 1.16
main: de.wiese_christoph.tnx.Main
softdepend: [Essentials]

commands:
     vote:
      description: Vote for day, night, clear or rain.
      usage: /<command> <day|night|clear|rain>
      permission: tnx.vote
     rocket:
      description: Launch a player in the air and let him explode.
      usage: /<command> <player>
      permission: tnx.rocket
     ce:
      description: Enable or disable Creeper Explosion protection.
      usage: /<command> <true|false>
      permission: tnx.ce
     bp:
      description: Enable or disable Bed Percentage night skip.
      usage: /<command> <true|false>
      permission: tnx.bp
     tv:
      description: Enable or disable Time Vote.
      usage: /<command> <true|false>
      permission: tnx.tve
     bb:
      description: Create a BossBar Broadcast Message.
      usage: /<command> <message>
      permission: tnx.bb
     volksabstimmung:
      description: Create a Volksabstimmung.
      usage: /<command> <minutes> <message>
      permission: tnx.poll
     di:
      description: Show the inventory of a player before he died.
      usage: /<command> [player]
      permission: tnx.di
     